# 2017 May 25
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: ruby
rvm:
  - "2.2"
install:
  - gem install travis --no-rdoc --no-ri
script:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/travis-another.bash)"
notifications:
  email:
    recipients:
      secure: NGw43fBO6uTm1F+NCV2x1hvKFDW7Ecg3aVU/vOrkptzgcYx4jS/j2wAWtIA8Grbxcnl8qtCypRhfnRcIsgzD/b6w7UqkhfnWxOO9/cMgD/5oVNKhIyCg52Kfr2tbpCiDpC4ODQI80+wQjw4zpQahEvYq9vY1l0cQo5LAnkNRGu8=
  slack:
    secure: IPqf2kcVUFnGVBXdB20WvA01XLKn1MbrOhcKB92OxUrHcD1QDSuSc+rgOQh/Sslh8TVGv8z3X9e89wG9hEis3Sp5/7inZc6y2JbVpwwJZczV3zJkerK45Zkiz2GoVt91P1Du03/KyTkQwVg3MhD0B2cvClgpCeIDQ5qG9OmlExg=
